# Generated by Django 4.1.6 on 2023-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, null=True, verbose_name='Announce'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Time of publishing'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
